[package]
name = "dofiles_manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.82"
handlebars = "5.1.2"
home = "0.5.9"
once_cell = "1.19.0"
toml = "0.8.12"
walkdir = "2.5.0"
